force-app/main/default/objects/AWS_Config__c/AWS_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will use to store user&apos;s credential for the AWS</description>
    <label>AWSConfig</label>
</CustomObject>

force-app/main/default/objects/AWS_Config__c/fields/AWS_Access_Key__c.field-meta.xml
<CustomField>
    <fullName>AWS_Access_Key__c</fullName>
    <label>AWS Access Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Config__c/fields/AWS_Secret_Access_Key__c.field-meta.xml
<CustomField>
    <fullName>AWS_Secret_Access_Key__c</fullName>
    <label>AWS Secret Access Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Config__c/fields/S3_Bucket_Name__c.field-meta.xml
<CustomField>
    <fullName>S3_Bucket_Name__c</fullName>
    <label>S3 Bucket Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Config__c/fields/S3_Region_Name__c.field-meta.xml
<CustomField>
    <fullName>S3_Region_Name__c</fullName>
    <label>S3 Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FileDownloadController.cls
public with sharing class FileDownloadController {
    public String fileContentType { get; set; }
    public Blob fileDownload { get; set; }

    public FileDownloadController() {
        String fileName = ApexPages.currentPage().getParameters().get('fileName');
        
        if (String.isBlank(fileName)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Missing file name'));
            return;
        }

        try {
            // AWS Config
            List<AWS_Config__c> configList = [SELECT Id, AWS_Access_Key__c, AWS_Secret_Access_Key__c, S3_Bucket_Name__c, S3_Region_Name__c, CreatedDate, LastModifiedDate FROM AWS_Config__c WITH SECURITY_ENFORCED LIMIT 1];
            if (!configList.isEmpty()) {
                AWS_Config__c configData = configList[0];
                String bucketName = configData.S3_Bucket_Name__c;
                Http http = new Http();
                HttpRequest request = new HttpRequest();
                request.setEndpoint('https://' + bucketName + '.s3.amazonaws.com/' + fileName);
                request.setMethod('GET');
                HttpResponse response = http.send(request);
    
                if (response.getStatusCode() == 200) {
                    fileDownload = response.getBodyAsBlob();
                    ApexPages.currentPage().getHeaders().put('Content-Disposition', 'attachment; filename="' + fileName + '"');
                } else {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Failed to download file from AWS'));
                }
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'AWS Configuration is not found'));
            }
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: ' + e.getMessage()));
        }
    }
}