force-app/main/default/objects/Chat__c/Chat__c.object-meta.xml
<CustomObject>
    <label>WB Chat</label>
    <nameField>
        <displayFormat>WB Chat {0}</displayFormat>
        <label>WB Chat Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WB Chats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chat__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>WB Chats</relationshipLabel>
    <relationshipName>WB_Chats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Date_of_Message__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Message__c</fullName>
    <label>Date of Message</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Message_Status__c.field-meta.xml
<CustomField>
    <fullName>Message_Status__c</fullName>
    <label>Message Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Seen</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Read</fullName>
                <isActive>false</isActive>
                <label>Read</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>Button</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
            <value>
                <fullName>Broadcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Reaction__c.field-meta.xml
<CustomField>
    <fullName>Reaction__c</fullName>
    <label>Reaction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat__c/fields/Type_of_Message__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Message__c</fullName>
    <label>Type of Message</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Messages</fullName>
            </value>
            <value>
                <fullName>Outbound Messages</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chat__c/fields/WhatsAppMessageId__c.field-meta.xml
<CustomField>
    <fullName>WhatsAppMessageId__c</fullName>
    <label>WhatsAppMessageId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>WB Template</label>
    <nameField>
        <displayFormat>WBC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WB Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template__c/fields/Header_Type__c.field-meta.xml
<CustomField>
    <fullName>Header_Type__c</fullName>
    <label>Header Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Image</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Document</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Template__c/fields/Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_Id__c</fullName>
    <externalId>true</externalId>
    <label>Template Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>520</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/Template_Variable__c.field-meta.xml
<CustomField>
    <fullName>Template_Variable__c</fullName>
    <label>Template Variable</label>
    <summaryForeignKey>Template_Variable__c.Template__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/WBHeader_Body__c.field-meta.xml
<CustomField>
    <fullName>WBHeader_Body__c</fullName>
    <label>WBHeader Body</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template__c/fields/WBTemplate_Body__c.field-meta.xml
<CustomField>
    <fullName>WBTemplate_Body__c</fullName>
    <label>WBTemplate Body</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Template_Variable__c/Template_Variable__c.object-meta.xml
<CustomObject>
    <label>WB Template Variable</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WB Template Variables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Variable__c/fields/Alternate_Text__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Text__c</fullName>
    <label>Alternate Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template_Variable__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template_Variable__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template_Variable__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>WB Template Variables</relationshipLabel>
    <relationshipName>WB_Template_Variables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Template_Variable__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Body</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChatWindowControllerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-04-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class ChatWindowControllerTest {

    @testSetup
    static void setup() {
        try {

            Account a = new Account (Name = 'Test Account');
            insert a;

            Contact testContact = new Contact(
                LastName = 'Test Contact', 
                AccountId = a.Id,
                Phone = '+911234567890'
            );
            insert testContact;

            Chat__c testChat = new Chat__c(
                Message__c = 'Test Message',
                Contact__c = testContact.Id,
                Type_of_Message__c = 'OutBound Messages',
                Message_Status__c = 'Sent',
                Date_of_Message__c = Date.today(),
                Message_Type__c = 'Text',
                Phone__c = '+911234567890'
            );
            insert testChat;
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{ 'className' => 'ChatWindowControllerTest', 'methodName' => 'setup', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null });
        }
    }

    @isTest
    static void testGetCombinedData() {
        try {
            Contact testContact = [SELECT Id FROM Contact LIMIT 1];

            Test.startTest();
            Map<String, Object> combinedData = ChatWindowController.getCombinedData(testContact.Id, 'Contact');
            Test.stopTest();

            list<Chat__c> chats = (list<Chat__c>) combinedData.get('chats');
            // System.assert( chats.size() > 0, 'Chats should be returned.');
            // System.assertEquals('Test Message', chats[0].Message__c, 'Chat message should match the test data.');
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{'className' => 'ChatWindowControllerTest', 'methodName' => 'testGetCombinedData', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null});
        }
    }

    @isTest
    static void testCreateChat() {
        try {
            Contact testContact = [SELECT Id, Phone FROM Contact LIMIT 1];

            Map<String, String> chatData = new Map<String, String>{
                'message' => 'Hello!',
                'templateId' => null,
                'messageType' => 'Text',
                'recordId' => testContact.Id,
                'replyToChatId' => null,
                'phoneNumber' => testContact.Phone
            };

            Test.startTest();
            Chat__c newChat = ChatWindowController.createChat(chatData);
            chatData.put('templateId', 'test');
            Chat__c wrongDataChat = ChatWindowController.createChat(chatData);
            Test.stopTest();

            System.assertNotEquals(null, newChat, 'New chat should be created.');
            System.assertEquals('Hello!', newChat.Message__c, 'Message should match the input.');
            System.assertEquals(testContact.Id, newChat.Contact__c, 'Contact ID should match.');
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{ 'className' => 'ChatWindowControllerTest', 'methodName' => 'testCreateChat', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null });
        }
    }

    @isTest
    static void testCreateChatWithImage() {
        try {
            Contact testContact = [SELECT Id, Phone FROM Contact LIMIT 1];

            ContentVersion contentVersion = new ContentVersion(
                Title = 'Test Image',
                VersionData = Blob.valueOf('Test Content'),
                PathOnClient = 'testImage.jpg'
            );
            insert contentVersion;
            ContentVersion cv = [SELECT Id FROM ContentVersion WHERE Title = 'Test Image' LIMIT 1];

            Map<String, String> chatData = new Map<String, String>{
                'message' => cv.Id,
                'templateId' => null,
                'messageType' => 'Image',
                'recordId' => testContact.Id,
                'replyToChatId' => null,
                'phoneNumber' => testContact.Phone
            };

            Test.startTest();
            Chat__c newChat = ChatWindowController.createChat(chatData);
            Test.stopTest();

            System.assertNotEquals(null, newChat, 'New chat should be created.');
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{ 'className' => 'ChatWindowControllerTest', 'methodName' => 'testCreateChatWithImage', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null });
        }
    }

    @isTest
    static void testUpdateReaction() {
        try {
            Chat__c testChat = [SELECT Id FROM Chat__c LIMIT 1];

            Test.startTest();
            Chat__c updatedChat = ChatWindowController.updateReaction(testChat.Id, 'Like');
            Chat__c wrongDataChat = ChatWindowController.updateReaction('test', 'Like');
            Test.stopTest();

            System.assertNotEquals(null, updatedChat, 'Chat should be updated.');
            System.assertEquals('Like', updatedChat.Reaction__c, 'Reaction should match the input.');
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{ 'className' => 'ChatWindowControllerTest', 'methodName' => 'testUpdateReaction', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null });
        }
    }

    @isTest
    static void testUpdateThemePreference() {
        try {

            Test.startTest();
            Boolean isSuccess = ChatWindowController.updateThemePreference('light');
            Test.stopTest();

            System.assertEquals(true, isSuccess, 'Custom setting should be created/updated successfully.');
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{ 'className' => 'ChatWindowControllerTest', 'methodName' => 'testUpdateThemePreference', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null });
        }
    }

    @isTest
    static void testSendWhatsappMessage() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Chat__c testChat = [SELECT Id FROM Chat__c LIMIT 1];

        String jsonData = '{"message": "Hello, this is a test message."}';

        ChatWindowController.sendWhatsappMessage(jsonData, testChat.Id, true, '<|USER|>');
        test.setMock(HttpCalloutMock.class, new TestSendMessage(200, '{"messaging_product":"whatsapp","contacts":[{"input":"testNum","wa_id":"testNumId"}],"messages":[{"id":"testId"}]}'));
        Test.startTest();
        Map<String, Object> result = ChatWindowController.sendWhatsappMessage(jsonData, testChat.Id, false, null);
        Test.stopTest();

        System.assertNotEquals(null, result.get('chat'), 'The result should not be null');
    }

    @isTest
    static void testSendWhatsappMessageFailed() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        Chat__c testChat = [SELECT Id FROM Chat__c LIMIT 1];
        String jsonData = '{"message": "Hello, this is a test message."}';
        test.setMock(HttpCalloutMock.class, new TestSendMessage(404, ''));
        Test.startTest();
        Map<String, Object> result = ChatWindowController.sendWhatsappMessage(jsonData, testChat.Id, false, null);
        Test.stopTest();

        System.assertNotEquals(null, result.get('chat'), 'The result should not be null');
    }

    @isTest
    static void testGetTemplateData() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];

        Template__c testTemplate = new Template__c(
            Template_Name__c = 'Test Template',
            Header_Type__c = 'Text',
            WBHeader_Body__c = 'Hello {{1}}',
            WBTemplate_Body__c = 'Hello {{1}}',
            Template_Id__c = 'testId'
        );
        
        insert testTemplate;

        Template_Variable__c testVariable = new Template_Variable__c(
            Name = '{{1}}',
            Field_Name__c = 'FirstName',
            Object_Name__c = 'Contact',
            Type__c = 'Body',
            Alternate_Text__c = 'name'
        );
        testVariable.Template__c = testTemplate.Id;
        insert testVariable;

        Template_Variable__c testVariable2 = new Template_Variable__c(
            Name = '{{1}}',
            Field_Name__c = 'Name',
            Object_Name__c = 'Account',
            Type__c = 'Header',
            Alternate_Text__c = 'name'
        );
        testVariable2.Template__c = testTemplate.Id;
        insert testVariable2;

        Test.startTest();
        ChatWindowController.getTemplateData(null, testContact.Id, 'Contact');
        Map<String, Object> result = ChatWindowController.getTemplateData(testTemplate.Id, testContact.Id, 'Contact');
        Test.stopTest();

        System.assertNotEquals(null, result.get('template'), 'The result should not be null');
    }

    @isTest
    static void testUpdateStatus(){
        try {
            Chat__c testChat = [SELECT Id FROM Chat__c LIMIT 1];
            testChat.WhatsAppMessageId__c = 'somethingId';

            List<String> messageIds = new List<String>();
            messageIds.add(testChat.Id);

            test.setMock(HttpCalloutMock.class, new testUpdateStatus(200));
            Test.startTest();
            ChatWindowController.updateStatus(messageIds);
            Test.stopTest();

            Chat__c resultChat = [SELECT Id FROM Chat__c WHERE Id =: testChat.Id LIMIT 1];

            System.assertEquals('Seen', resultChat.Message_Status__c, 'The chat status should be updated.');
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{ 'className' => 'ChatWindowControllerTest', 'methodName' => 'testUpdateStatus', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null });
        }
    }

    @isTest
    static void testCreateChatForAWSFiles() {
        try {
            Contact testContact = [SELECT Id, Phone FROM Contact LIMIT 1];

            Map<String, String> chatData = new Map<String, String>{
                'message' => 'Hello!',
                'fileName' => 'test.pdf',
                'mimeType' => 'application/pdf',
                'messageType' => 'Document',
                'recordId' => testContact.Id,
                'replyToChatId' => null,
                'phoneNumber' => testContact.Phone
            };

            Test.startTest();
            Chat__c newChat = ChatWindowController.createChatForAWSFiles(chatData);
            Test.stopTest();

            System.assertNotEquals(null, newChat, 'New chat should be created.');
        } catch (Exception e) {
            ExceptionHandler.logException(new Map<String, Object>{ 'className' => 'ChatWindowControllerTest', 'methodName' => 'testCreateChatForAWSFiles', 'exceptionObj' => e, 'isApiException' => false, 'statusCode' => null, 'chatId' => null, 'moreDetails' => e.getMessage(), 'apiResponse' => null });
        }
    }

    public class TestSendMessage implements HttpCalloutMock {

        Integer statusCode;
        String body;

        TestSendMessage(Integer statusCode, String body){
            this.statusCode = statusCode;
            this.body = body;
        }

        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(body);
            res.setStatusCode(statusCode);
            return res;
        }
    }

    public class TestUpdateStatus implements HttpCalloutMock {

        Integer statusCode;

        TestUpdateStatus(Integer statusCode){
            this.statusCode = statusCode;
        }

        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('test');
            res.setStatusCode(statusCode);
            return res;
        }
    }
}